name: de
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Run Build"
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Running deploy"
