name: D1

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/chekout@v3
      - run: pwd
      - run: whoami
      - run: hostname
      - run: ls -la
      - run: uname -a
